apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mindwm-touch-huyach
  namespace: context-purple
spec:
  template:
    spec:
      containers:
      - env:
        - name: NEO4J_BOTL_URL
          value: bolt://neo4j:password@purple-neo4j-neo4j.context-purple:7687
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-opentelemetry-collector.monitoring-ng:4317
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://tempo-distributor.monitoring-ng:4317/v1/traces
        image: 10.20.30.11:8080/mindwm-touch-huyach:0.2.0@sha256:87b59aae323f189322a529458a7c1d24f7e1da9d2379e4b550909802ae01341b
