apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knfunc
  namespace: context-name
spec:
  template:
    spec:
      containers:
        - image: repo/knfunc:version@digest
          env: []
