apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: knfunc-demo-trigger
  namespace: context-purple
spec:
  broker: context-broker-purple
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: context-broker-purple-dead-letter
        namespace: context-purple
  filter: {}
  filters:
  - any:
    - exact:
        type: touch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knfunc-demo
      namespace: context-purple
